### ISSUE TITLE
Basic Structure

### ISSUE THREAD

**Issue by zbqmal** [ArtHub-AH/arthub-web#2]
1. Intro
- Create and build the basic structure of AH project

2. Acceptance Criteria
- [x] AHWEB-001 Create Project
- [x] AHWEB-002 Build Basic Main Page
- [x] AHWEB-003 Build Basic Search Page
- [x] AHWEB-004 Build Basic Profile Page
- [x] AHWEB-005 Build Basic Additional Pages And Make Connections
